# ---------- STAGE 1: builder ----------
FROM golang:1.24.13-bookworm AS builder

WORKDIR /app

# копируем модульные файлы
COPY go.mod go.sum ./
RUN go mod download


COPY internal/db-service ./internal/db-service
COPY cmd/db ./cmd/db
COPY pkg/apperrors ./pkg/app_errors
COPY pkg/context_key ./pkg/context_key
COPY pkg/kafka_logger ./pkg/kafka_logger
COPY pkg/models ./pkg/models


RUN CGO_ENABLED=0 GOOS=linux go build -o /app/db ./cmd/db


# ---------- финальный образ ----------
FROM alpine:3.21.3
WORKDIR /app
COPY --from=builder /app/db .
EXPOSE 8081
CMD ["./db"]
